name: ${name}
version: '${version}'
main: ${main}
api-version: '${apiversion}'
description: 'Allows server command blocks /console to transfer users between Velocity servers'
website: 'https://www.sulltec.com'
authors: ['Drako Trogdor']
contributors: ['Drako Trogdor']
depend: []
softdepend: []
loadbefore: []
provides: []
